# tasks file for 2do_parcial

---

- name: Crear estructura de directorios en un solo comando
  become: yes
  file:
    path: "/tmp/2do_parcial/alumno"
    state: directory
    mode: '0755'
    recurse: yes

- name: Crear estructura de directorios en un solo comando
  become: yes
  file:
    path: "/tmp/2do_parcial/equipo"
    state: directory
    mode: '0755'
    recurse: yes

- name: generar archivo datos_alumno.txt
  become: yes
  template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt
    mode: '0755'

- name: generar archivo datos_equipo.txt
  become: yes
  template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt
    mode: '0755'

- name: Configurar sudoers para el grupo 2PSupervisores sin contrase√±a
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%2PSupervisores'
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
